{
 "title": "Solar",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Prod today",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "expr": "today_watthours",
     "measurement": "readings",
     "select": [
      [
       { "params": [ "today_watthours" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "production" }
     ]
    }
   ]
  },
  {
   "title": "Cons today",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "expr": "consumption_today_watthours{type=\"total-consumption\"}",
     "measurement": "readings",
     "select": [
      [
       { "params": [ "today_watthours" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "total-consumption" }
     ]
    }
   ]
  },
  {
   "title": "Net today",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "expr": "consumption_today_watthours{type=\"total-consumption\"} - ignoring(type) production_today_watthours{type=\"eim\"}",
     "measurement": "readings",
     "select": [
      [
       { "params": [ "today_watthours" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "net-consumption" }
     ]
    }
   ]
  },
  {
   "title": "Prod 7 days",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "expr": "production_7days_watthours",
     "measurement": "readings",
     "select": [
      [
       { "params": [ "7days_watthours" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "production" }
     ]
    }
   ]
  },
  {
   "title": "Cons 7 days",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 0 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "expr": "consumption_7days_watthours{type=\"total-consumption\"}",
     "measurement": "readings",
     "select": [
      [
       { "params": [ "7days_watthours" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "total-consumption" }
     ]
    }
   ]
  },
  {
   "title": "Net 7day",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 0 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "expr": "consumption_7days_watthours{type=\"total-consumption\"} - ignoring(type) production_7days_watthours{type=\"eim\"}",
     "measurement": "readings",
     "select": [
      [
       { "params": [ "7days_watthours" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "net-consumption" }
     ]
    }
   ]
  },
  {
   "title": "Production Lifetime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "expr": "production_lifetime_watthours{type=\"eim\"}",
     "measurement": "readings",
     "select": [
      [
       { "params": [ "lifetime_watthours" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "production" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(type) (power_now_watts)",
     "groupBy": [
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "readings",
     "select": [
      [
       { "params": [ "power_now_watts" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "production" }
     ]
    }
   ]
  },
  {
   "title": "Average power by inverter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(serial, location) (inverter_last_report_watts)",
     "groupBy": [
      { "params": [ "serial" ], "type": "tag" }
     ],
     "legendFormat": "{{location}} {{serial}}",
     "measurement": "inverter_readings",
     "select": [
      [
       { "params": [ "last_report_watts" ], "type": "field" }
      ]
     ]
    },
    {
     "expr": "max (inverter_max_report_watts)",
     "groupBy": [
      { "params": [ "serial" ], "type": "tag" }
     ],
     "measurement": "inverter_readings",
     "select": [
      [
       { "params": [ "max_report_watts" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total power by array",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(location) (inverter_last_report_watts)",
     "groupBy": [
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "inverter_readings",
     "select": [
      [
       { "params": [ "last_report_watts" ], "type": "field" }
      ]
     ]
    },
    {
     "expr": "max(sum by(location) (inverter_max_report_watts))",
     "groupBy": [
      { "params": [ "location" ], "type": "tag" }
     ],
     "legendFormat": "Max per array power",
     "measurement": "inverter_readings",
     "select": [
      [
       { "params": [ "max_report_watts" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}